### ISSUE TITLE
assocparser QC check: check annotation not in blacklist subsets (gorule-0000008)

### ISSUE THREAD

**Issue by cmungall** [biolink/ontobio#154]
https://github.com/geneontology/go-site/issues/551

Different ontologies have different blacklist subsets; GO has 2

Documented here:
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000008.md

Let's start with a GO-specific check at parse time. It won't affect other ontologies as only GO uses these subsets. 

We'd like to do this in SPARTA but until mechanism in place let's do this parse-time

**Comment by dougli1sqrd** [comment]
Is this documented for GO terms by those terms in the SQL query? Or should we still use the property (gocheck_do_not_annotate) on the GO terms?

**Comment by cmungall** [comment]
ignore the SQL: https://github.com/geneontology/go-site/pull/560
