### ISSUE TITLE
Test Failure at test_local_json.py::test_local_json_parse

### ISSUE THREAD

**Issue by dougli1sqrd** [biolink/ontobio#158]
When `make travis_test` is run, the titled test fails. 

The test loads the pato.json ontology from `tests/resources/`, and then asks for `"PATO:0001374"`. In the ontobio/networkx code, this amounts to taking the built networkx graph, called `graph` and:
```
graph.node["PATO:0001374"]
```
This raises a KeyError.

In a python interpreter, I printed out the networkx nodes with:
```
for n in graph:
    print(n)
```

And the list returned was full of ids that looked like:
```
OBO:PATO_0001336
OBO:PATO_0000004
OBO:PATO_0000488
OBO:PATO_0000487
```

Repeating the test asking instead for OBO:PATO_0001374 (`graph.node["OBO:PATO_0001374"]`), I get a returned result.

This suggests that the mapping of ids somehow changed, but the networkx version has been what it is for a while. This issue looks like the weirdness how rdflib is weird about prefixes, but I don't think rdflib is being used.
.

**Comment by cmungall** [comment]
it's curie_util from prefixcommons that is being used

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/160 For the fix. 
ontobio 0.2.34 out.
