### ISSUE TITLE
Question: When there are no valid taxons, we accept all taxons

### ISSUE THREAD

**Issue by dougli1sqrd** [biolink/ontobio#18]
In `_validate_taxon()` if in the config there are no valid taxons, or `self.config.valid_taxa is None` we accept all taxons. This seems counterintuitive, since wouldn't that mean that there does not exist a taxon that is valid?

**Comment by cmungall** [comment]
It's perhaps unfortunate that the python reserved term in `None`, but really we mean unset, ie client does not care. How else should we indicate this? We could do a string like `*` (ugh), force the user to enumerate all possibilities (not desirable) or use a scala-esque object `NotSet | List` which is not very pythonesque....

**Comment by cmungall** [comment]
We'll retain the current behavior - an empty whitelist means accept all
