### ISSUE TITLE
Update GOlr API URL

### ISSUE THREAD

**Issue by kltm** [biolink/ontobio#191]
The currently used URL is no longer supported in any meaningful way and may be outdated.

We should now have http://golr-aux.geneontology.io available. This is meant to be the API/download server for the GO. What are you using currently for biolink? This should have shorter downtimes and http://amigo-aux.geneontology.io can be monitored separately.

tagging @deepakunni3

**Comment by kltm** [comment]
It is also on a more robust machine, updated on a more-or-less monthly basis, with only a few minutes of planned downtime.

**Comment by selewis** [comment]
@deepakunni3 <https://github.com/deepakunni3>, this (I believe) is (a)
simple to do and (for sure) (b) quite urgent.

Can you get it working this morning? Please.

**Comment by deepakunni3** [comment]
@selewis Yes, definitely :)

URL updated in `conf/config.yaml` and can be tracked via the following PR: https://github.com/biolink/ontobio/pull/192
Will release a new version of Ontobio that includes the new changes.

**Comment by selewis** [comment]
Super @deepakunni3, I'm ready to try it as soon as you give me the green light. Hopefully today?

**Comment by kltm** [comment]
Just checking that this has been tested--the old URL had some odd mappings needed by @nathandunn that are not included here; I'd want to make sure that this is not "bug accurate".

**Comment by nathandunn** [comment]
@kltm  Can you specify what those might be?

**Comment by nathandunn** [comment]
Are these the Apollo ones?

**Comment by kltm** [comment]
@nathandunn yes. That said, @deepakunni3 has already dug in a little more and is making the appropriate changes.

**Comment by nathandunn** [comment]
Awesome.   Thanks all.

**Comment by selewis** [comment]
Hi @kltm @deepakunni3 - So (from ribbon) I'm looking at https://api.monarchinitiative.org/api/ with the query below, but I'm not seeing >1 'with'. Still just getting the PTNid and nothing else (i.e. none of the experimental). Is this really finished to completion or are their additional steps remaining:

https://api.monarchinitiative.org/api/bioentityset/slimmer/function?&slim=GO:0003824&slim=GO:0004872&slim=GO:0005102&slim=GO:0005215&slim=GO:0005198&slim=GO:0008092&slim=GO:0003677&slim=GO:0003723&slim=GO:0001071&slim=GO:0036094&slim=GO:0046872&slim=GO:0030246&slim=GO:0003674&slim=GO:0008283&slim=GO:0071840&slim=GO:0051179&slim=GO:0032502&slim=GO:0000003&slim=GO:0002376&slim=GO:0050877&slim=GO:0050896&slim=GO:0023052&slim=GO:0010467&slim=GO:0019538&slim=GO:0006259&slim=GO:0044281&slim=GO:0050789&slim=GO:0042592&slim=GO:0007610&slim=GO:0008150&slim=GO:0005576&slim=GO:0005737&slim=GO:0005856&slim=GO:0005739&slim=GO:0005634&slim=GO:0005694&slim=GO:0016020&slim=GO:0031982&slim=GO:0071944&slim=GO:0030054&slim=GO:0042995&slim=GO:0032991&slim=GO:0045202&slim=GO:0005575&subject=ZFIN:ZDB-GENE-131127-632

**Comment by deepakunni3** [comment]
@selewis The PR has been merged but we still need to release Ontobio (@dougli1sqrd)

Once we have a release, we need to ping @kshefchek to update the BioLink-API on https://api.monarchinitiative.org/api to use the latest version of Ontobio for the new URL changes to take effect

**Comment by selewis** [comment]
Thanks, got it. Bated breath here.

**Comment by deepakunni3** [comment]
@selewis The BioLink-API on Monarch has been updated to use the latest Ontobio (with the fixes).

Thanks @kshefchek and @dougli1sqrd

**Comment by kltm** [comment]
@deepakunni3 Does this include a user agent string?

**Comment by kltm** [comment]
No, nevermind.

**Comment by deepakunni3** [comment]
@kltm That will have to come in as a separate PR. I was aiming to rush the URL changes in first.
