### ISSUE TITLE
Implement gorule-0000013 Taxon checks

### ISSUE THREAD

**Issue by dougli1sqrd** [biolink/ontobio#218]
Taxon checks should be implemented as a qc rule in ontobio. This would be in the ontobio/io/qc.py.

See ticket https://github.com/geneontology/go-site/issues/758

**Comment by dustine32** [comment]
@kltm @cmungall Anyone know exactly how I can pull the taxon constraints out of the GO ontology? Or is it in a different ontology? I can sparql the "never_in_taxon" (RO:0002161) triples out of rdf.geneontology.org so I know they get loaded from somewhere.

Though, if I can't get access to this source, I could just sparql from within the GoRule.

Thanks!

**Comment by kltm** [comment]
@dustine32 Well, this check will actually have to be implemented in the python parsing at some level. It may be best to defer this to tomorrow's call and talk about the issue a little more generally (@cmungall ).

**Comment by dustine32** [comment]
Sweet! Will talk tomorrow, thanks!

**Comment by cmungall** [comment]
Dependent on: https://github.com/balhoff/gaferencer/issues/1

once done @dougli1sqrd can add to go pipeline and take results and integrate into ontobio reporting

**Comment by dougli1sqrd** [comment]
Taxon checks are now implemented in ontobio. PR here: https://github.com/biolink/ontobio/pull/357
