### ISSUE TITLE
Change JSON file reports during GAF parsing to support better reporting

### ISSUE THREAD

**Issue by kltm** [biolink/ontobio#219]
The current JSON output is lacking lacking in a few key aspects to support the reporting that we'd like to have in the GO.

We'd like to have the following changes to the output:

- [x] the top-level fields include `group` (resource)
- [x] the violations are grouped by either their rule (id) or a catch-all
- [ ] the violations include `species` (taxon id)

(I may be forgetting one.)

There may be an arbitrary cut-off per rule of listed violations.

Tagging @dougli1sqrd and @cmungall

**Comment by dougli1sqrd** [comment]
```
{
    "group": "goa_chicken_complex",
    "lines": 1234,
    "skipped_lnes": 24,
    "messages": {
        "other": [
            {
                "level": "WARNING",
                "line": "Hello\tworld\tgoterm\tetc",
                "type": "INVALID_ASPECT",
                "message": "Wrong aspect",
                "obj": "GO:1234567",
                "taxon": "NCBITaxon:12345"
            },
            {
                "etc": "etc"
            }
        ],
        "gorule-0000001": [
            {
                "level": "ERROR",
                "line": "not\tenough\tcolumns",
                "type": "Wrong number of columns in this line",
                "message": "Line has 3 columns, when it should have 15 or 17",
                "obj": "",
                "taxon": ""
            }
        ]
    }
}
```
I do something like this.

**Comment by dougli1sqrd** [comment]
So, if a gaf has more than one taxon, which one do I use? Do I use all of them? @cmungall @kltm

**Comment by dougli1sqrd** [comment]
Hello @kltm and @cmungall,

This PR for ontobio does this: https://github.com/biolink/ontobio/pull/226
This PR for go-site cleans up any issues with the new format: https://github.com/geneontology/go-site/pull/779

We have a successful build in Jenkins: https://build.geneontology.org/job/geneontology/job/pipeline/job/json_format_test/4/ which uses this code.

This is the output combined report: http://skyhook.berkeleybop.org/json_format_test/reports/combined.report.json

And this is an example of WB report.json: http://skyhook.berkeleybop.org/json_format_test/reports/wb.report.json

Let's have discussion here. If this is good, let's merge and release ontobio, and then at the same time merge the go-site PR.

**Comment by kltm** [comment]
I think the question for me is: if we take this now, will be be able to back out or fix quickly enough to deal with this month's release?

**Comment by dougli1sqrd** [comment]
I think so. At worst we can roll back go-site and ontobio. And I have higher confidence since we have a passing build and a successful combined report that plays well with the downloads page generation and such. Can you confirm that the downloads page is good? http://skyhook.berkeleybop.org/json_format_test/products/pages/downloads.html

Actually, it looks like annotations aren't going through in the downloads page? Maybe I need to tweak the mustache template for the downloads page?

**Comment by kltm** [comment]
If we can, let's go through skyhook real fast and double check products. If we agree it looks right, the PRs can be merged?

**Comment by dougli1sqrd** [comment]
@kltm @cmungall I think we can close this?

**Comment by kltm** [comment]
@dougli1sqrd To clarify, we now have the ability to group reports by group *and* species?

**Comment by dougli1sqrd** [comment]
This ticket seems to just say errors are grouped by `group`, are identified by what rule they violate or if no other rule, and `other` case if no rule violation found, and the violation messages include a field for `species`. I believe these are all true. My understanding is that this is about the json format?

**Comment by dougli1sqrd** [comment]
All relavent PRs for this ticket have been closed. All rule messages have group and species, and so could be grouped by species or group. (We don't currently do this, but the fact is we *could*)
