### ISSUE TITLE
OWL/RDF  Format

### ISSUE THREAD

**Issue by moh55m55** [biolink/ontobio#267]
Does ontobio support this format OWL/RDF ? if so how to load it from disk?

**Comment by cmungall** [comment]
See: https://ontobio.readthedocs.io/en/latest/inputs.html

Currently it can

 * read an ontology from a remote triple store via SPARQL, but currently this has to be ontobee (could be adapted)
 * read an obojson file natively
 * read a file in any OWL syntax (RDF/XML, Turtle, Manchester, OBO), but this requires owltools (https://github.com/owlcollab/owltools/) to be installed. It will launch owltools CLI to convert from owl to obojson. This is not ideal.

I recommend converting to obojson ahead of time using the well-support http://robot.obolibrary.org toolkit
