### ISSUE TITLE
Add filter for sources of gene-to-disease tables

### ISSUE THREAD

**Issue by monicacecilia** [biolink/ontobio#287]
Add a filter to the 'gene-to-disease' views, requiring the presence of at least one of a set of sources in support of the association; currently `OMIM, Orphanet, GWAS Catalog, OMIA`. This will remove 'gene-to-disease' associations where `CTD, ClinVar`, or `Coriell` are the only sources.

For background and details, please consult with @kshefchek and this PR ([# 1637](https://github.com/monarch-initiative/monarch-app/pull/1637)) in the monarch-ui repo. 

This is a blocker to our ability to display correct results in the Monarch Initiative website. 

Assigned to: @deepakunni3 
Priority: HIGH! (by @cmungall)

**Comment by monicacecilia** [comment]
When completed, this will close # 39 at monarch-ui (https://github.com/monarch-initiative/monarch-ui/issues/39).

**Comment by cmungall** [comment]
A bit better to do this in the API rather than the UI, but this has to be fixed at the data layer, otherwise other people consuming our graph will get the junk

**Comment by kshefchek** [comment]
We now index causal and non causal associations in separate docs with different association types, so I think this can be replaced with https://github.com/biolink/biolink-api/issues/274
