### ISSUE TITLE
NCIT and HPO terms associated with terms with ontobio

### ISSUE THREAD

**Issue by RS060115** [biolink/ontobio#291]
There is a problem using ontobio: for four terms that we have found, there are both NCIT and HPO terms.

Example:
neoplasm
NCIT:C3262
HPO:0002664

the four terms that we have found:
neoplasm
hemangioma
lymphoma
papilloma

this is causing a problem when we use ontobio.

**Comment by cmungall** [comment]
I'm not totally sure what you mean. This seems like an issue in the ontology not ontobio. Which ontology are you parsing?

Note it's not even strictly a problem in the ontology. There is no guarantee that classes have globally unique labels

**Comment by RS060115** [comment]
Thank you. We were parsing HPO. We are surprised that there is not a global 1:1 matching. Is there a reason for this? It seems that it would be convenient to have a 1:1 mapping between terms and IDs.
Thank you for the help.

**Comment by cmungall** [comment]
Do you want to raise a comment here: https://github.com/obophenotype/human-phenotype-ontology/issues/

I'm closing this as I don't think there is an ontobio issue
