### ISSUE TITLE
Implement GO Rules using the GoAssociation model data sctructures

### ISSUE THREAD

**Issue by dougli1sqrd** [biolink/ontobio#295]
Currently the GoRule classes in the `qc` module assume the association data coming in is just a list. This would be the columns of a GAF or something. But I'm realizing that this is *only* implemented for GAFs essentially. If we want this set of rules to work on anything converted to an Association, GoRules should work on Associations, rather than the split gaf line. This makes it general to gpad and gaf automatically. 

This will require in `qc.py`:
- [x] refactoring each `test` method of `GoRule` subclasses to take `GoAssociation`s
- [x] re-implement each `test` to correctly use incoming GoAssociations
- [x] tests to be re-written to use GoAssociation (maybe write a helper function to do this)
- [x] ensure that `test_go_rules` will accept GoAssociation

This necessarily spawns work in GafParser and AssocParser, but should be captured in other tickets.

**Comment by kltm** [comment]
@dougli1sqrd For the time being, I virtually added this to https://github.com/orgs/geneontology/projects/31 as a note. While it doesn't show up here, if you could move it along that would be helpful.

**Comment by kltm** [comment]
To clarify: could you manually move the note to the right as you complete--you are personally fine where you are.

**Comment by dougli1sqrd** [comment]
PR here: https://github.com/biolink/ontobio/pull/412
