### ISSUE TITLE
Downloader and parser should be able to work with both compressed and uncompressed annotation sources

### ISSUE THREAD

**Issue by kltm** [biolink/ontobio#296]
Currently, the downloader would not be able to handle a GAF or GPAD source that was uncompressed--some mechanisms rely on the assumption that they are compressed (gzipped). Fixing this ticket would be at least allowing upstream annotation providers to seamlessly use either compressed or uncompressed sources.

For requirements for how this would fit into the GO data pipeline, all savable byproducts of a run should be compressed, regardless of what the upstream was.

Note the connection making https://github.com/geneontology/go-site/issues/997 easy for people.

**Comment by dougli1sqrd** [comment]
This is completed with https://github.com/biolink/ontobio/pull/300 as of ontobio version 1.8.0
