### ISSUE TITLE
Make sure Soft/Warning gorules are not filtering

### ISSUE THREAD

**Issue by dougli1sqrd** [biolink/ontobio#329]
Pointed out in https://github.com/geneontology/go-site/issues/1086 it was noticed that an SGD annotation was missing, but was caught by gorule 18. However, gorule 18 is a Soft/Warning check and should not filter anything. 

Here we see that https://github.com/biolink/ontobio/blob/master/ontobio/io/gafparser.py#L249 is skipping all rules defined in `qc.py` regardless of report level - an obvious mistake and a bug.

The task is to correct this line to not skip the line on warnings.

**Comment by pgaudet** [comment]
This seems high priority, since it's filtering out valid annotations. Will it get done by the next release?

**Comment by dougli1sqrd** [comment]
fixed
