### ISSUE TITLE
Improve performance of ontol.get_ancestors when relations are passed

### ISSUE THREAD

**Issue by cmungall** [biolink/ontobio#335]
Currently when we pass in a list of relations to an ontol object, a new networkx graph is created, with that set of relations. This incurs a large performance penalty at the outset while the subgraph is constructed. The client can avoid this by building these subgraphs in advance but this is awkward.

We should just implement relation-aware ancestors ourselves. I had originally thought that nx would provide a fast C implementation but on cursory examination that appears not to be the case.

**Comment by dougli1sqrd** [comment]
for https://github.com/biolink/ontobio/pull/343
