### ISSUE TITLE
Cachier is not thread safe and causes problems in some environments

### ISSUE THREAD

**Issue by deepakunni3** [biolink/ontobio#358]
Most recently, the GO team has had cachier crash in a multi-process environment when using the rdfgen command line.

In general, cachier does not work well in many environments and should be replaced with something safer.

Noting that #321 is to make cachier optional. However, this ticket proposed closing that and removing it as it is not safe.

Tagging @dougli1sqrd @kltm (ghost wrote this issue) @cmungall

**Comment by deepakunni3** [comment]
Based on a quick discussion with @kltm and @cmungall , the decision is to remove cachier completely as the benefits are not worth the hassle.
We will have a more deliberate caching mechanism, one where user has more control, and the caching behavior is explicitly defined.

**Comment by dougli1sqrd** [comment]
The suggestion is to remove it, and then later add a different caching mechanism?

**Comment by kltm** [comment]
That is what I got from the conversation with @cmungall and @deepakunni3 .

**Comment by dougli1sqrd** [comment]
Cool cool. I agree.

**Comment by cmungall** [comment]
yes. More explicit caching, allow command line user to save ontology as
pickle file, allow pickled ontology to be loaded using normal ontology load
mechanisms

**Comment by kshefchek** [comment]
Caching is pretty important for calls to owlsim, here are some benchmarks comparing no caching vs diskcache:
[cache-comparison.txt](https://github.com/biolink/ontobio/files/3511463/cache-comparison.txt)

**Comment by cmungall** [comment]
OK we can restore it for owlsim for now (I assume you don't need to cache
the ontology loading part, just the web service calls). This won't affect
the GO pipeline.

I don't know where that leaves us with the Translator workflows
