### ISSUE TITLE
Notebooks not loading

### ISSUE THREAD

**Issue by lpalbou** [biolink/ontobio#374]
I was trying to load the phenotype enrichment notebook (https://github.com/biolink/ontobio/blob/master/notebooks/Phenotype_Enrichment.ipynb) but it doesn't load.

Also tried other notebooks and don't load either:
![Screen Shot 2019-09-19 at 3 59 47 PM](https://user-images.githubusercontent.com/24249870/65287055-8df58a80-daf6-11e9-9ac7-d5018cbfc3dd.png)

Seems like a S3 file may be missing

**Comment by deepakunni3** [comment]
@lpalbou This is a GitHub issue. Probably temporary.

**Comment by lpalbou** [comment]
Yep it's back. It could have been a S3 temporary unavailability of GitHub files
