### ISSUE TITLE
ontobio-parse-assocs.py omits version header line from output

### ISSUE THREAD

**Issue by dustine32** [biolink/ontobio#465]
Originating issue - https://github.com/geneontology/pipeline/issues/198

Specifically, the top line `!gaf-version: 2.1` is being dropped/not added to the output GAF. Looks like this is because the outfile isn't set [when initializing the writer](https://github.com/biolink/ontobio/blob/1d0470f9267c8aa306de2d55d6a09f0a8c6fc15c/bin/ontobio-parse-assocs.py#L198-L208), which is when the header is written:

https://github.com/biolink/ontobio/blob/1d0470f9267c8aa306de2d55d6a09f0a8c6fc15c/ontobio/io/assocwriter.py#L208

https://github.com/biolink/ontobio/blob/1d0470f9267c8aa306de2d55d6a09f0a8c6fc15c/ontobio/io/assocwriter.py#L51-L55

Passing `outfile` into `GafWriter()` in [ontobio-parse-assocs.py](https://github.com/biolink/ontobio/blob/1d0470f9267c8aa306de2d55d6a09f0a8c6fc15c/bin/ontobio-parse-assocs.py#L202) should fix this.

**Comment by dougli1sqrd** [comment]
Merged into ontobio since version 1.19.3 here: https://github.com/biolink/ontobio/pull/466
