### ISSUE TITLE
Ontobio should not pin dependencies to a particular version

### ISSUE THREAD

**Issue by deepakunni3** [biolink/ontobio#482]
Currently the latest release of Ontobio has the following dependencies pinned to a fixed version:
```
marshmallow==3.0.0b11
pysolr==3.6.0
networkx==2.2
matplotlib==2.0.0
SPARQLWrapper==1.8.0
scipy==1.2.0
plotly==2.0.7
```

This creates problems when Ontobio is being used as a dependency for downstream applications.
Is it possible to have all these be `>=`?
Or are there unexpected side effects that disrupts Ontobio's functionality?

**Comment by dhimmel** [comment]
Looking through `install_requires`, I noticed the same thing (several pinned dependencies):

https://github.com/biolink/ontobio/blob/61878238d0d6eb4dccb4b48a285f7b9ae5eac5f4/setup.py#L46-L62

This makes ontobio likely to be incompatible with many user environments. For example, networkx is currently at version 2.5.

Solutions might be:

- pin install_requires only to major versions or nothing at all.
- run scheduled CI jobs that will detect if dependency updates break things.

**Comment by matentzn** [comment]
Is there anyone that can look into this? It really makes ontobio incompatible with many other libraries.

**Comment by matentzn** [comment]
(For me its networkx)

**Comment by deepakunni3** [comment]
@matentzn https://github.com/biolink/ontobio/pull/585 should fix the above issue
