### ISSUE TITLE
requirements.txt requiring networkx 2.2

### ISSUE THREAD

**Issue by saramsey** [biolink/ontobio#506]
Hi Deepak,

Just an FYI, the `requirements.txt` file for ontobio (in the master branch) appears to be hard-coded to use networkx 2.2, but that version of networkx is (I think) not compatible with python3.9. It looks like you recently merged in some code changes to update ontobio's usage of networkx; am wondering if you can update the requirements.txt accordingly?  Am assuming that it should not be `==2.2` ?

Kindly,
Steve & Team Expander Agent

**Comment by saramsey** [comment]
See the issue we are having with using the current pypi version of ontobio, with python3.9:
https://github.com/RTXteam/RTX/issues/1179

**Comment by saramsey** [comment]
forgot to tag @deepakunni3

**Comment by deepakunni3** [comment]
@saramsey Thanks for pointing this out. 

We will make a new release of ontobio which will not pin networkx to a fixed version.
