### ISSUE TITLE
pip install of ontobio-0.2.10.tar.gz fails

### ISSUE THREAD

**Issue by diekhans** [biolink/ontobio#54]
This is on mac/os..  pandoc is installed, but this seems like a heavy-weight requirement.

`
 pip install ontobio
Collecting ontobio
  Downloading ontobio-0.2.10.tar.gz (78kB)
    100% |████████████████████████████████| 81kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    pandoc: /private/var/folders/_z/t1f6j2317kq4fcspgcyd2_780000gn/T/pip-build-iry9_6/ontobio/README.md: openFile: does not exist (No such file or directory)
    README.md conversion to reStructuredText failed. Error:
    Command '('pandoc', '--from', 'markdown', '--to', 'rst', '/private/var/folders/_z/t1f6j2317kq4fcspgcyd2_780000gn/T/pip-build-iry9_6/ontobio/README.md')' returned non-zero exit status 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_z/t1f6j2317kq4fcspgcyd2_780000gn/T/pip-build-iry9_6/ontobio/setup.py", line 28, in <module>
        with open(readme_path) as read_file:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/_z/t1f6j2317kq4fcspgcyd2_780000gn/T/pip-build-iry9_6/ontobio/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_z/t1f6j2317kq4fcspgcyd2_780000gn/T/pip-build-iry9_6/ontobio/
`

**Comment by diekhans** [comment]
Can't install from source because of a similar problem with prefixcommons. 
The github URL on pypi for prefix commons: https://github.com/biolink-api/prefixcommons
is not correct.

'
pip install -r requirements.txt 
Collecting marshmallow>=0.0 (from -r requirements.txt (line 1))
  Downloading marshmallow-2.13.5-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 2.7MB/s 
Collecting prefixcommons>=0.0 (from -r requirements.txt (line 2))
  Downloading prefixcommons-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    pandoc: /private/tmp/pip-build-bT7lwN/prefixcommons/README.md: openFile: does not exist (No such file or directory)
    README.md conversion to reStructuredText failed. Error:
    Command '('pandoc', '--from', 'markdown', '--to', 'rst', '/private/tmp/pip-build-bT7lwN/prefixcommons/README.md')' returned non-zero exit status 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-bT7lwN/prefixcommons/setup.py", line 27, in <module>
        with open(readme_path) as read_file:
    IOError: [Errno 2] No such file or directory: '/private/tmp/pip-build-bT7lwN/prefixcommons/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-bT7lwN/prefixcommons/
'

**Comment by cmungall** [comment]
you're right, we'll fix the github URL

I wonder why this only shows up sometimes, @realmarcin saw this too. However, whenever we have done a 

```
pip install -r requirements.txt
```

it always works

@dougli1sqrd can you take a look?

aside: the whole pandoc to convert md to rst during install is kinda awkward, I wonder if we should just use rst for all our python projects.

**Comment by dougli1sqrd** [comment]
I was always in a virtual environment when I install.

I think just for installing you shouldn't need to convert rst to md and back or anything.  

Make sure also that it's pip3 doing the install and python3 environment. So I always would do:

    $ python3 -m venv env
    $ source env/bin/activate
    $ pip3 install ontobio==0.2.10

This works for me. If from source, I do everything the same except I also `pip3 install requirements.txt` and I `pip3 install .` instead of naming ontobio.

**Comment by dougli1sqrd** [comment]
@diekhans what system are you on?

**Comment by diekhans** [comment]
ah, bingo; I was accidentally using python 2.7

It's weird that setup.py didn't complain about py2 or at lest
get a syntax error. It looks like it's trying to run pandoc
before even entering.

Maybe a check for not being on py3 would be in order?

**Comment by diekhans** [comment]
https://stackoverflow.com/questions/13924931/setup-py-restrict-the-allowable-version-of-the-python-interpreter

has a trivial check.

**Comment by diekhans** [comment]
It would be useful to put in a check for the supported python version, as this is not obvious.

I will make a PR.

**Comment by diekhans** [comment]
The root cause seems to be that the source .tar.gz doesn't pip install at all, even with python 3.
Using pip3 caused it to grab the wheel from pypi, which does install.  

It seems fragle to run pandoc every time setup is run.  It could be done only during the build and include the RST file in the source dist.  Perhaps simpler is just convert change the source from
README.md to README.rst. 

e.g. https://github.com/biocommons/eutils

**Comment by diekhans** [comment]
p.s. please reopen this ticket, this is a time waste for someone starting with the package and it would be best to resolve it.

**Comment by dougli1sqrd** [comment]
@diekhans @cmungall Is this ticket fixed at this point?

**Comment by cmungall** [comment]
We no longer use pandoc, so I believe so
