### ISSUE TITLE
Add missing relations to relations.py

### ISSUE THREAD

**Issue by dustine32** [biolink/ontobio#548]
Originating from https://github.com/geneontology/pipeline/issues/220#issuecomment-822848683.

To accommodate MGI annotations, we need to add some relations to the lookup in ontobio. This will prevent errors like:
```
ERROR - Syntax error in annotation extension field: extensions should be relation(curie)
```
Due to the relation not being recognized. Here are the missing relations:

involved_in_positive_regulation_of (RO:0002429)
starts (RO:0002223)
starts_with (RO:0002224)
ends_with (RO:0002230)

Tagging @dougli1sqrd

**Comment by dustine32** [comment]
For completion, might as well also add:

ends (RO:0002229)
involved_in_regulation_of (RO:0002428)
involved_in_negative_regulation_of (RO:0002430)

**Comment by dougli1sqrd** [comment]
Just merged https://github.com/biolink/ontobio/pull/549

We can do a release today.

**Comment by dustine32** [comment]
@dougli1sqrd Thank you!
