### ISSUE TITLE
Graph.node removed in networkX 2.4

### ISSUE THREAD

**Issue by kshefchek** [biolink/ontobio#554]
See https://networkx.org/documentation/stable/release/release_2.4.html#deprecations

We currently use this in obograph_util.  I suggest we anchor to 2.3 and then fix this.  This is breaking the monarch ui evidence views.

**Comment by matentzn** [comment]
Can we fix this issue in the code? Having ontobio pin versions really makes it hard to have it co-exist with other libraries further down the stack.

**Comment by deepakunni3** [comment]
@kshefchek Could you also let us know if PR #585 fixed the issues you were seeing with Monarch UI evidence views?

**Comment by cmungall** [comment]
Thank you @deepakunni3 for #585 !!!

**Comment by kshefchek** [comment]
everything is working on the monarch side, thanks @deepakunni3 !

**Comment by deepakunni3** [comment]
Happy to help @cmungall! Glad that it was quick fix.

Thanks @kshefchek for checking 🎉
