### ISSUE TITLE
Change CURIE of exists_during in lookup

### ISSUE THREAD

**Issue by dustine32** [biolink/ontobio#572]
The relation `exists_during` has recently been minted an RO term ID that's now being used in the MGI import GPAD. We need to change the value in the `relations.py` lookup from http://purl.obolibrary.org/obo/GOREL_0000032 to http://purl.obolibrary.org/obo/RO_0002491.

**Comment by sierra-moxon** [comment]
I see this change in relations.py, and I don't find GOREL_0000032 -- closing? :)
