### ISSUE TITLE
filter-out EVIDENCE option needs to produce a file with the lines lines filtered with that evidence

### ISSUE THREAD

**Issue by dougli1sqrd** [biolink/ontobio#60]
So on an ontobio-parse-assocs.py run, with the `--filter-out IEA` option, we should build a file with all the lines included, and one called group_name_noiea.gaf.

**Comment by cmungall** [comment]
how should we do this to avoid hardcoding ad-hoc assumptions about filenames?

How about adding a different parameter

```
--filter-from <CODE> <FILE>
```

e.g.

```
--filter-from IEA foo_noiea.gaf
```

**Comment by dougli1sqrd** [comment]
well we have a `-o` output file some/file/at/location/group.gaf. We can then just say for some `--filter-out CODE` we can write out a `some/fileat/location/group_noCODE.gaf`. Since if we don't include an output file, we probably similarly don't want a noCODE.gaf file.

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/66 Does this with the `--filtered-file` option
