### ISSUE TITLE
Converting GPAD to GAF can result in blank evidence codes if no ECO-to-GAF mapping exists

### ISSUE THREAD

**Issue by dustine32** [biolink/ontobio#620]
Coming from https://github.com/geneontology/go-site/issues/1847 and potentially related to https://github.com/geneontology/pipeline/issues/283.

The `GpadParser` currently allows creation of `GoAssociation` objects with evidence ECO codes that do not [directly map](https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping.txt) to a GAF code (e.g. IDA, ISO) so that, when writing these out to GAF, it will result in a blank evidence code column.

We should throw an error on any GPAD line that uses one of these unmapped ECO codes (e.g. `ECO:0006003`). A flag can be created to bypass this check but the default will be to fail these lines.

Tagging @kltm

**Comment by kltm** [comment]
For those reading along: this would generate an error in the report as well, and would not be silent (which is partially the issue now for some cases).
