### ISSUE TITLE
problems parsing output from latest obographs library

### ISSUE THREAD

**Issue by balhoff** [biolink/ontobio#697]
In GO, we are trying to update to the latest obographs in ROBOT. We have been using owltools, which uses an older obographs release. We noticed this change, which currently upsets the ontobio JSON reader:

owltools:

```json
{
      "definedClassId" : "http://purl.obolibrary.org/obo/GO_0101013",
      "genusIds" : [ "http://purl.obolibrary.org/obo/GO_0005248", "http://purl.obolibrary.org/obo/GO_0008381" ],
      "restrictions" : [ ]
}
```

robot:

```json
{
      "definedClassId" : "http://purl.obolibrary.org/obo/GO_0101013",
      "genusIds" : [ "http://purl.obolibrary.org/obo/GO_0005248", "http://purl.obolibrary.org/obo/GO_0008381" ]
}
```

owltools outputs an empty `restrictions` array, but the newer obographs leaves it out. As pointed out by @cmungall in [my issue at obographs](https://github.com/geneontology/obographs/issues/110), all properties in a JSON schema are optional unless marked required. So ontobio should be able to handle a missing `restrictions` and treat it as an empty list. I think there are other properties that will trigger this, so the same fix should be applied to all list handling.

cc @kltm @sierra-moxon

**Comment by kltm** [comment]
Shadowed as "draft" item in: https://github.com/orgs/geneontology/projects/135

**Comment by balhoff** [comment]
For the ontology build we need to move to the latest version of ROBOT, to stay compatible with the latest Protege, and also to take advantage of new OBO format features which impact several different open issues in the ontology repo. Currently we use owltools for this step (the JSON change is actually in older versions of ROBOT as well), but to help manage technical debt we would like to eliminate owltools from the ontology build.

**Comment by pgaudet** [comment]
It would be nice if the priority of this could be increased, since we need it to finally move to the latest version of Protege. 

@cmungall @kltm  is this something @sierra-moxon could do?

**Comment by kltm** [comment]
@pgaudet It looks like @sierra-moxon self-assigned this issue a little bit ago. I think with other priorities, this has just not been picked up yet. Maybe after some of the current GO work is done, before starting in on the next bit of API work (which would be to expose more GO-CAM in the API), this could be prioritized (if you consider this more pressing)?

**Comment by pgaudet** [comment]
That sounds perfect.

**Comment by kltm** [comment]
@sierra-moxon @balhoff I wanted to confirm if this was indeed closed, or if there were other steps necessary to call this "done"?

**Comment by balhoff** [comment]
It sounds fixed to me.
