### ISSUE TITLE
ontobio gaf parser should reject extensions that have invalid IDs

### ISSUE THREAD

**Issue by cmungall** [biolink/ontobio#99]
MGI GAF:

```
MGI     MGI:1354727     Smtn            GO:0060452      MGI:MGI:4437553|PMID:18678771   IMP     MGI:MGI:3613292 P       smoothelin              protein taxon:10090     20170906        MGI   occurs_in(EMAPA:35342),occurs_in(MA:0002039 TS28)
MGI     MGI:1354727     Smtn            GO:0060452      MGI:MGI:4437553|PMID:18678771   IMP     MGI:MGI:3613293 P       smoothelin              protein taxon:10090     20170906        MGI   occurs_in(EMAPA:35342),occurs_in(MA:0002039 TS28)
```

the contents of the parentheses should be an ID, no spaces.

In these case we can assume the core annotation is good, but either the entire extension conjunction, or the offending element must be removed, with suitable warning reported

**Comment by kltm** [comment]
Cheers! Restarting pipeline.

**Comment by cmungall** [comment]
Now released to pypi

**Comment by hdrabkin** [comment]
Just looked at this; in the gaf at my end the TS28 was not removed from the EMAPA term, it was removed from the MA term.
